### ISSUE TITLE
wish: support for logging proxy commands

### ISSUE THREAD

**Issue by markstos** [open-ch/log-user-session#3]
I'd like to use this on bastion host, where the common use case is that users transparently ssh /through/ the machine. A client configuration might look like this:

```
Host target-host
     ProxyCommand ssh --W %h:%p bastion
```

This currently generates no logging on the bastion host where `log-user-session` is installed when I expected it would. I tried installing it both in the main `sshd_config` file as well as the `authorized_keys` file for a user, with the same result.

**Comment by markstos** [comment]
To be clear, all I really want to see is that  "User /bob/ proxied to machine /foo/ at time /Y/". I'm not expecting to capture any of what happens on the remote machine.

**Comment by markstos** [comment]
From my understanding of this related Q&A, a `ForceCommand` can't be used to control a `ProxyCommand`. It sounds like the `ProxyCommand` will get run first, and the `ForceCommand` will never get run.

**Comment by markstos** [comment]
I confirmed that there is already logging for the _incoming_ part of the proxy'ed connections through the OS logging that I find in `/var/log/auth.log` in Ubuntu, which looks like this:

```
Feb 17 15:04:09 localhost sshd[2993]: Accepted publickey for xxx from 1.2.3.4 port 33924 ssh2: DSA 
Feb 17 15:04:09 localhost sshd[2993]: pam_unix(sshd:session): session opened for user xxx by (uid=0)
```

It would be nice to have the _outgoing_ part of the proxy command logged as well, but it appears that it may not be possible.

**Comment by kbucheli** [comment]
This cannot be done by this tool as it operates outside of sshd while when using -W all is done by sshd.
A option is to use netcat instead of -W to achieve the same. Then you leave sshd and now you can intercept with ForceCommand.
For logging this I probably only want one line per session in one log file and thus I would not use this tool which creates one file per session.
My suggestion would be to crate an own little shell script which does the logging and then execs the netcat to the final destination. For inspiration see
http://www.wallix.org/2011/10/18/restricting-remote-commands-over-ssh/

**Comment by markstos** [comment]
Thanks for the feedback!
